name: Install Python CDK
description: Install Python CDK
runs:
  using: "composite"
  steps:
    - name: Install CDK from npm
      uses: actions/setup-node@v3 # CDK command is installed as NPM module
      with:
        node-version: 18
      run: |
        npm install -g aws-cdk
      shell: bash
    - name: Install Python CDK lib
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
      run: |
        pip install aws-cdk-lib
      shell: bash
