name: Install AWS CLI v2
description: Install AWS CLI v2 for Linux
runs:
  using: "composite"
  steps:
    - name: Install AWS CLI v2
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version
      shell: bash
