name: Infrastructure Stack Workflow

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened]

jobs:
  deploy-infra-stack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/composite/install-python-cdk
    - name: CDK Deploy Infra Stack
      run: | 
        echo 'cdk synth InfraStack'
        echo 'cdk diff InfraStack'
        echo 'cdk deploy InfraStack'
